name: test action1

on:
  workflow_dispatch:
    inputs:
      version:
          description: 'opis'
          default: '0.0.0'
          required: true
          type: string


jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:

      - name: Install all deps
        run: |
          echo "cos leci ${{ github.event.inputs.version }}"
           
